seo:
  description:
  keywords:
  social_image:
  hide-from-google:

paths:
  uploads: assets/uploads
  data: _data
  layouts: _layouts
  includes: _includes

collections_config:
  data:
    path: _data
    output: false
    filter:
      exclude:
        - socials.yml
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false

_inputs:
  seo:
    type: object
    options:
      preview:
        text:
          - key: "Search Engine"
        subtext:
          - key: "Edit meta data for seach optimization"
  layout:
    type: auto
    hidden: true
    cascade: true
  text-placement:
    type: auto
    hidden: true
    cascade: true
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true

_select_data:
  data_config:
    site-settings:
_structures: {}
_editables: {}
data_config: {}
timezone: America/Los_Angeles
