paths:
  uploads: assets/uploads
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    filter:
      exclude:
        - socials.yml
_inputs:
  layout:
    hidden: true
  hero:
    hidden: true
  hero-r:
    hidden: true
  price:
    hidden: true
  wkshop-background:
    label: Color Scheme
    type: select
    options:
      values:
        - dark blue
        - light blue
  text-placement:
    hidden: true
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  data_config:
    site-settings:
_structures: {}
_editables: {}
data_config: {}
timezone: America/Los_Angeles