- title: Classes
  description: 'Heat Up Your Practice: From Gentle Vinyasa to Intense Hot Yoga.'
  image: /assets/uploads/fl3a4757.jpg
  link: classes
- title: Workshops
  description: 'Unearth New Skills: Immerse in Sound Healing, Breathwork, and Beyond.'
  image: /assets/uploads/gianna.jpeg
  link: trainings
- title: YTT
  description: 'Ignite Your Yoga Potential: 200-Hour Teacher Training Journey.'
  image: /assets/uploads/fl3a4803.jpg
  link: teachertraining 