seo:
  site_name: Indie Yoga
  title: Indie Yoga Ocean Beach CA
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username: indieyogasd
  facebook_url:
  twitter_username:
