seo:
  site_name: Indie Yoga
  title: Indie Yoga Ocean Beach CA
  description:
  keywords:
  social_image:
  favicon_image:
  author: ViaSana.co
social:
  instagram_username: indieyogasd
  facebook_url: